import re

def validar_legajo(legajo):
    return re.fullmatch(r"[0-9]{5}", legajo) 
def validar_codigo(codigo):
    return re.fullmatch(r"[A-Z]{2}[0-9]{4}", codigo) 

def validar_telefono(telefono):
    return re.fullmatch(r"[0-9]{4}-[0-9]{4}", telefono) 

def validar_correo(correo):
    return re.fullmatch(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", correo) 

def validar_importe(importe):
    return re.fullmatch(r"\$[0-9]+", importe) 

def validar_patente(patente):
    return re.fullmatch(r"([A-Z]{3}[0-9]{3}|[A-Z]{2}[0-9]{3}[A-Z]{2})", patente) 

print("\n")
print("validar_legajo")
print("casos válidos:")
print(f"legajo 12320: {validar_legajo('12320')}") # al pasarle el parámetro a funciónes regex debe ser cad. (comillas).
print(f"legajo 55432: {validar_legajo('55432')}")
print(f"legajo 00001: {validar_legajo('00001')}")
print("\t")
print("casos inválidos:")
print(f"legajo 148: {validar_legajo('148')}")
print(f"legajo 123456: {validar_legajo('123456')}")
print(f"legajo 12a45: {validar_legajo('12a45')}")
print(f"cadena vacía: {validar_legajo('')}")
print("\n")
print("validar_codigo")
print("casos válidos:")
print(f"código 'AS1234': {validar_codigo('AS1234')}")
print(f"código 'XY9999': {validar_codigo('XY9999')}")
print(f"código 'AB0000': {validar_codigo('AB0000')}")
print("\n")
print("casos inválidos:")
print(f"código as1234: {validar_codigo('as1234')}")
print(f"código A1234: {validar_codigo('A1234')}")
print(f"código ABC1234: {validar_codigo('ABC1234')}")
print(f"cadena vacía: {validar_codigo('')}")
print("\n")
print("validar_telefono-")
print("casos válidos:")
print(f"teléfono 1234-5678: {validar_telefono('1234-5678')}")
print(f"teléfono 4444-9999: {validar_telefono('4444-9999')}")
print(f"teléfono 0000-1111: {validar_telefono('0000-1111')}")
print("\n")
print("casos inválidos:")
print(f"teléfono 123-5678: {validar_telefono('123-5678')}")
print(f"teléfono 12345678: {validar_telefono('12345678')}")
print(f"teléfono 1234_5678: {validar_telefono('1234_5678')}")
print(f"cadena vacía '': {validar_telefono('')}")
print("\n")
print("validar_correo")
print("casos válidos:")
print(f"correo hola@gmail.com: {validar_correo('hola@gmail.com')}")
print(f"correo cris.yanes05@gmail.com: {validar_correo('cris.yanes05@gmail.com')}")
print(f"correo hola@uade.edu.ar: {validar_correo('hola@uade.edu.ar')}")
print("\n")
print("casos inválidos:")
print(f"correo hola.com: {validar_correo('hola.com')}")
print(f"correo hola@gmail.com.c: {validar_correo('hola@gmail.com.c')}")
print(f"cadena vacía '': {validar_correo('')}")
print("\n")
print("validar_importe:")
print("casos válidos:")
print(f"importe $100: {validar_importe('$100')}")
print(f"importe $1: {validar_importe('$1')}")
print(f"importe $50000: {validar_importe('$50000')}")
print("casos inválidos:")
print(f"importe 100: {validar_importe('100')}")
print(f"importe $: {validar_importe('$')}")
print(f"importe $10a0: {validar_importe('$10a0')}")
print(f"cadena vacía '': {validar_importe('')}")
print("\n")
print("validar_patente")
print("casos válidos:")
print(f"patente ABC123: {validar_patente('ABC123')}")
print(f"patente AA123BB: {validar_patente('AA123BB')}")
print(f"patente ZZ999YY: {validar_patente('ZZ999YY')}")
print("\n")
print("casos inválidos:")
print(f"patente abc123: {validar_patente('abc123')}")
print(f"patente AB1234: {validar_patente('AB1234')}")
print(f"patente A123456: {validar_patente('A123456')}")
print(f"cadena vacía '': {validar_patente('')}")
print("\n")



